# Generated by Django 3.1.4 on 2020-12-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segun_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='home_address',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='dob',
            field=models.DateField(default='12/12/2000'),
        ),
    ]
